PARALLEL: true
VALIDATE_ALL_CODEBASE: false
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
REPORT_OUTPUT_FOLDER: none
ENABLE_LINTERS:
  - YAML_PRETTIER
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - PYTHON_MYPY
  - PYTHON_BLACK
  - PYTHON_PYRIGHT
PYTHON_PYRIGHT_ARGUMENTS: "--strict"
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_BLACK_ARGUMENTS: "--line-length=88"
